<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableSdkContainerDebugging>True</EnableSdkContainerDebugging>
    <ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:8.0</ContainerBaseImage>
    <DockerfileContext>..\Synapse</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\IntroPagesContent\css\main.css" />
    <None Include="wwwroot\IntroPagesContent\css\services.css" />
    <None Include="wwwroot\IntroPagesContent\fonts\icon_vectra---.eot" />
    <None Include="wwwroot\IntroPagesContent\fonts\icon_vectra---.svg" />
    <None Include="wwwroot\IntroPagesContent\fonts\icon_vectra---.ttf" />
    <None Include="wwwroot\IntroPagesContent\fonts\icon_vectra---.woff" />
    <None Include="wwwroot\IntroPagesContent\fonts\icon_vectra.eot" />
    <None Include="wwwroot\IntroPagesContent\fonts\icon_vectra.svg" />
    <None Include="wwwroot\IntroPagesContent\fonts\icon_vectra.ttf" />
    <None Include="wwwroot\IntroPagesContent\fonts\icon_vectra.woff" />
    <None Include="wwwroot\IntroPagesContent\fonts\Inter-Bold.woff" />
    <None Include="wwwroot\IntroPagesContent\fonts\Inter-Medium.woff" />
    <None Include="wwwroot\IntroPagesContent\fonts\Inter-Regular.woff" />
    <None Include="wwwroot\IntroPagesContent\fonts\Inter-SemiBold.woff" />
    <None Include="wwwroot\IntroPagesContent\images\appt-calendar-clock.svg" />
    <None Include="wwwroot\IntroPagesContent\images\arabic.svg" />
    <None Include="wwwroot\IntroPagesContent\images\benefits-interface.svg" />
    <None Include="wwwroot\IntroPagesContent\images\bottom.png" />
    <None Include="wwwroot\IntroPagesContent\images\comprehensive-dashboards.svg" />
    <None Include="wwwroot\IntroPagesContent\images\credit-management.svg" />
    <None Include="wwwroot\IntroPagesContent\images\customer-personalization.svg" />
    <None Include="wwwroot\IntroPagesContent\images\dots.gif" />
    <None Include="wwwroot\IntroPagesContent\images\down_arrow.svg" />
    <None Include="wwwroot\IntroPagesContent\images\english.svg" />
    <None Include="wwwroot\IntroPagesContent\images\fast_sms.svg" />
    <None Include="wwwroot\IntroPagesContent\images\group-people.png" />
    <None Include="wwwroot\IntroPagesContent\images\responsive-ui.svg" />
    <None Include="wwwroot\IntroPagesContent\images\rocket-inphone.svg" />
    <None Include="wwwroot\IntroPagesContent\images\shortLogo.svg" />
    <None Include="wwwroot\IntroPagesContent\images\sms.svg" />
    <None Include="wwwroot\IntroPagesContent\images\stay-ontrack.svg" />
    <None Include="wwwroot\IntroPagesContent\images\support_girl.jpg" />
    <None Include="wwwroot\IntroPagesContent\images\synapselogo.svg" />
    <None Include="wwwroot\IntroPagesContent\images\whatsp.svg" />
    <None Include="wwwroot\IntroPagesContent\pdf\spam-regulation-1.pdf" />
    <None Include="wwwroot\IntroPagesContent\pdf\spam-regulation-2.pdf" />
    <None Include="wwwroot\IntroPagesContent\pdf\spam-regulation-ar.pdf" />
    <None Include="wwwroot\IntroPagesContent\pdf\spam-regulation-en.pdf" />
    <None Include="wwwroot\IntroPagesContent\pdf\spam-regulation-en_old.pdf" />
    <None Include="wwwroot\IntroPagesContent\pdf\spam-regulation.pdf" />
    <None Include="wwwroot\IntroPagesContent\pdf\terms.docx" />
    <None Include="wwwroot\IntroPagesContent\pdf\terms_conditions.pdf" />
    <None Include="wwwroot\IntroPagesContent\pdf\terms_conditions_old.pdf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClientHTTPConsuming.Utilities\ClientHTTPConsuming.Utilities.csproj" />
    <ProjectReference Include="..\Core.DBAccess\Core.DBAccess.csproj" />
    <ProjectReference Include="..\Core.Models\Core.Models.csproj" />
    <ProjectReference Include="..\Synapse.Web.Campaign\Synapse.Web.Campaign.csproj" />
    <ProjectReference Include="..\SynapseAPI\SynapseAPI.csproj" />
  </ItemGroup>

</Project>
