
namespace Core.Models.Dtos.CommonDtos
{
    public class LocalizationResponse
    {
        public string AccountLogin { get; set; }
        public string AccountManager { get; set; }
        public string AccountManagerAlreadyExist { get; set; }
        public string AccountManagerCreation { get; set; }
        public string AccountManagerMap { get; set; }
        public string AccountManagerView { get; set; }
        public string Action { get; set; }
        public string Active { get; set; }
        public string ActiveStatus { get; set; }
        public string Add { get; set; }
        public string AddASingleContact { get; set; }
        public string AddCampaignTimings { get; set; }
        public string AddConnections { get; set; }
        public string AddContacts { get; set; }
        public string AddContactsfromaFile { get; set; }
        public string AddCustomer { get; set; }
        public string AddCustomerCredits { get; set; }
        public string AddDNDList { get; set; }
        public string AddDNDNumbers { get; set; }
        // public string AddDNDList { get; set; }
        public string AddedOn { get; set; }
        public string AddFilterWords { get; set; }
        public string AddFilterWordsView { get; set; }
        public string AddGroup { get; set; }
        public string AddMapSender { get; set; }
        public string AddMOMapShortCode { get; set; }
        public string AddNewKeyword { get; set; }
        public string AddPreferredRoute { get; set; }
        public string AddRateCard { get; set; }
        public string Address { get; set; }
        public string AddressRange { get; set; }
        public string AddressRangeNPI { get; set; }
        public string AddressRangeTon { get; set; }
        public string AddRoute { get; set; }
        public string AddSenderIDShortCode { get; set; }
        public string AddSMPPMaster { get; set; }
        public string AddTestSMSC { get; set; }
        public string AddVendorMaster { get; set; }
        public string AdministratorView { get; set; }
        public string AdminOperations { get; set; }
        public string All { get; set; }
        public string AllowDuplicateNumbers { get; set; }
        public string AllowedSpecialCharacters { get; set; }
        public string AllowTransactionalCampaigns { get; set; }
        public string AlreadyExists { get; set; }
        public string Alreadyftppathassigendtoanotheralerttype { get; set; }
        public string AlreadymappedwithCampaign { get; set; }
        public string Analytics { get; set; }
        public string ApplyChanges { get; set; }
        public string Areyousureactiverecord { get; set; }
        public string Areyousureinactiverecord { get; set; }
        public string Areyousuretodeleteselectedcontacts { get; set; }
        public string Areyousurewanttoproceed { get; set; }
        public string Areyousureyouwanttochangethestatus { get; set; }
        public string AssignPrivileges { get; set; }
        public string AtleastAddOneNumber { get; set; }
        public string Attachment { get; set; }
        public string Attempts { get; set; }
        public string AuthenticationType { get; set; }
        public string AutoConnection { get; set; }
        public string AvailableCredits { get; set; }
        public string AverageTPS { get; set; }
        public string Bind { get; set; }
        public string BODY { get; set; }
        public string BulkCustomSMS { get; set; }
        public string BulkSMS { get; set; }
        public string Business { get; set; }
        public string BusinessEmail { get; set; }
        public string ByPassDNDList { get; set; }
        public string ByPassDNSList { get; set; }
        public string Campaign { get; set; }
        public string CampaignActivity { get; set; }
        public string CampaignConfigurationView { get; set; }
        public string CampaignDeactivatedSuccessfully { get; set; }
        public string CampaignDetailed { get; set; }
        public string CampaignDetailedReportbetween { get; set; }
        public string CampaignDetailReport { get; set; }
        public string CampaignName { get; set; }
        public string Campaignnamealreadyexistedindb { get; set; }
        public string CampaignPausedSuccessfully { get; set; }
        public string CampaignReports { get; set; }
        public string CampaignReportStatus { get; set; }
        public string CampaignResumedSuccessfully { get; set; }
        public string Campaigns { get; set; }
        public string CampaignSummary { get; set; }
        public string CampaignSummaryReports { get; set; }
        public string CampaignSummery { get; set; }
        public string CampaignSuspendedSuccessfully { get; set; }
        public string CampaignTimings { get; set; }
        public string Campaigntimingsalreadyexists { get; set; }
        public string CampaignTimingsView { get; set; }
        public string CampaignType { get; set; }
        public string CantAssignPostPaidCreditType { get; set; }
        public string CCaddressshouldcontainsMobilenumberwithdomainnameandSMSmessageshouldbeinthebody { get; set; }
        public string CCEmail { get; set; }
        public string ChangePassword { get; set; }
        public string ChangePasswordonFirstLogin { get; set; }
        public string ChangeStatus { get; set; }
        public string Character { get; set; }
        public string CharacterS { get; set; }
        public string Charset { get; set; }
        public string Check { get; set; }
        public string Clear { get; set; }
        public string ClickHEREtoaddmobilenumber { get; set; }
        public string ClickHeretoaddRoute { get; set; }
        public string ClickHeretoaddSMPPIPDetails { get; set; }
        public string CommonWords { get; set; }
        public string Component { get; set; }
        public string ComposeQuickSMS { get; set; }
        public string ConfirmPassword { get; set; }
        public string ConfirmPasswordNotmatchedwithgivenPassword { get; set; }
        public string ConnectionName { get; set; }
        public string Connections { get; set; }
        public string Consolation { get; set; }
        public string Contactalreadyexistswiththegivendetails { get; set; }
        public string ContactNumber { get; set; }
        public string ContactPerson { get; set; }
        public string Contacts { get; set; }
        public string Contactsdeletedsuccessfully { get; set; }
        public string Counry { get; set; }
        public string Country { get; set; }
        public string CountryAddedSuccessfully { get; set; }
        public string CountryMaster { get; set; }
        public string CountrynotAdded { get; set; }
        public string CountryNotaddedContactyourSystemAdmin { get; set; }
        public string CountrynotAddedISDCode { get; set; }
        public string CountrynotUpdated { get; set; }
        public string CountrynotUpdatedISDCode { get; set; }
        public string CountryUpdateSuccessfully { get; set; }
        public string CouponNumber { get; set; }
        public string CreateaContactList { get; set; }
        public string CreateCampaign { get; set; }
        public string CreatedBy { get; set; }
        public string CreateKeyword { get; set; }
        public string Creatingfailedtoinformation { get; set; }
        public string CreditAllocationonlyforPrepaidCustomer { get; set; }
        public string CreditManagement { get; set; }
        public string Credits { get; set; }
        public string CreditType { get; set; }
        public string Currency { get; set; }
        public string CurrentBalance { get; set; }
        public string CustExpired { get; set; }
        public string CustInActive { get; set; }
        public string Customer { get; set; }
        public string Customeralreadyexistedindb { get; set; }
        public string CustomerAlreadyExists { get; set; }
        public string CustomerCreation { get; set; }
        public string Customercreationcountelapsed { get; set; }
        public string CustomerCredits { get; set; }
        public string CustomerExpired { get; set; }
        public string CustomerExpirydateexceeded { get; set; }
        public string CustomerisinInActivestate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPreference { get; set; }
        public string CustomerPreferences { get; set; }
        public string CustomerPreferencesareinInActiveState { get; set; }
        public string Customers { get; set; }
        public string CustomerType { get; set; }
        public string CustomerView { get; set; }
        public string CustomSMS { get; set; }
        public string CustPrefInActive { get; set; }
        public string CommonMessages { get; set; }
        public string Click { get; set; }
        public string commaseparatedmobilenumbers { get; set; }
        public string Completed { get; set; }
        public string ComposeTestSMSC { get; set; }
        public string ConnectionsView { get; set; }
        public string ContactsGroupNameshouldbespecifiedintheSubjectandSMSmessageshouldbespecifiedinthebody { get; set; }
        public string ContactsView { get; set; }
        public string CountryView { get; set; }
        public string Coupon { get; set; }
        public string CreateEmailTemplate { get; set; }
        public string CreateToCustomerCount { get; set; }
        public string CreditsPerMsg { get; set; }
        public string CurrentLocation { get; set; }
        public string CustomerCreditsView { get; set; }
        public string Dashboard { get; set; }
        public string DatanotAvailable { get; set; }
        public string Datanotexistsinuploadedfile { get; set; }
        public string datanotfound { get; set; }
        public string Date { get; set; }
        public string DateTime { get; set; }
        public string Days { get; set; }
        public string DCS { get; set; }
        public string Default { get; set; }
        public string DefaultRoutealreadyExists { get; set; }
        public string DefaultTemplates { get; set; }
        public string DeliveryRate { get; set; }
        public string DeliveryReport { get; set; }
        public string Department { get; set; }
        public string Description { get; set; }
        public string Destination { get; set; }
        public string DestNPI { get; set; }
        public string DestTon { get; set; }
        public string DigitsOnly { get; set; }
        public string DispatchSenderID { get; set; }
        public string DNDList { get; set; }
        public string Download { get; set; }
        public string DuplicateFilterWords { get; set; }
        public string DUPLICATEMOBILENOs { get; set; }
        public string DuplicateMobileNumber { get; set; }
        public string DuplicateName { get; set; }
        public string Duplicaterecord { get; set; }
        public string DuplicateRecordsContainUploadedFile { get; set; }
        public string Day { get; set; }
        public string Delete { get; set; }
        public string DeleteFile { get; set; }
        public string DeliveryReportRequired { get; set; }
        public string DirectOutBound { get; set; }
        public string DispatchType { get; set; }
        public string DNDListView { get; set; }
        public string Domain { get; set; }
        public string DownloadLookupResultFiles { get; set; }
        public string EmailSignature { get; set; }
        public string EmailTemplatePreview { get; set; }
        public string Enabled { get; set; }
        public string ExporttoExcel { get; set; }
        public string Email { get; set; }
        public string EmailAddressBusiness { get; set; }
        public string EmailAddressTechnical { get; set; }
        public string EmailConfigurationsSuccessfullyconnected { get; set; }
        public string EmailFormat { get; set; }
        public string EmailSubject { get; set; }
        public string EmailTemplate { get; set; }
        public string EmailToSMS { get; set; }
        public string Encryption { get; set; }
        public string End { get; set; }
        public string EndDate { get; set; }
        public string EndDateshouldnotbelessthantostartdate { get; set; }
        public string Endtag { get; set; }
        public string EnglishArabic { get; set; }
        public string EnquiryInterval { get; set; }
        public string Entries { get; set; }
        public string Error { get; set; }
        public string ErroringeneratingXML { get; set; }
        public string ErrorInSavingInformation { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorResponse { get; set; }
        public string ErrorwhileInsertion { get; set; }
        public string ExceptionOccured { get; set; }
        public string ExcludingCountryCode { get; set; }
        public string ExportContacts { get; set; }
        public string ExporttoCSV { get; set; }
        public string ExporttoPDF { get; set; }
        public string Failedtoapproved { get; set; }
        public string Failedtodeletecontact { get; set; }
        public string Failedtosaveinformation { get; set; }
        public string Failedtoupdate { get; set; }
        public string Failedtoupdateinformation { get; set; }
        public string FailedtoUpdateyourrequest { get; set; }
        public string Fax { get; set; }
        public string FeaturesprivilegesSetup { get; set; }
        public string FileDeletedSuccessfully { get; set; }
        public string FileName { get; set; }
        public string Fileshouldcontainheaderinformation { get; set; }
        public string FilterByRecords { get; set; }
        public string FilterWord { get; set; }
        public string FilterWords { get; set; }
        public string FirstName { get; set; }
        public string Footer { get; set; }
        public string FooterNotes { get; set; }
        public string Formats { get; set; }
        public string Forward { get; set; }
        public string ForwardBox { get; set; }
        public string ForwardDate { get; set; }
        public string ForwardType { get; set; }
        public string ForwardURL { get; set; }
        public string FristPrize { get; set; }
        public string From { get; set; }
        public string FromAliesName { get; set; }
        public string FromDate { get; set; }
        public string FromEmail { get; set; }
        public string FromtimeshouldbelessthanTotime { get; set; }
        public string FailedRecords { get; set; }
        public string Features { get; set; }
        public string FinanceCustomerSummary { get; set; }
        public string FinanceSummary { get; set; }
        public string FinanceVendorSummary { get; set; }
        public string Finish { get; set; }
        public string ForwardURLSMPP { get; set; }
        public string FromAliasname { get; set; }
        public string Generatedby { get; set; }
        public string GenerateVIPConfig { get; set; }
        public string Go { get; set; }
        public string GroupCreatedBy { get; set; }
        public string GroupsView { get; set; }
        public string GenarateasaGroupofXML { get; set; }
        public string GenarateClientConfig { get; set; }
        public string GenarateServerConfig { get; set; }
        public string Generate { get; set; }
        public string GivenInformationisWrong { get; set; }
        public string GroupAlreadyExists { get; set; }
        public string GroupName { get; set; }
        public string Groups { get; set; }
        public string HLRLookup { get; set; }
        public string HLRLookupSingle { get; set; }
        public string HLRLookupUpload { get; set; }
        public string HostName { get; set; }
        public string Hours { get; set; }
        public string Hrs { get; set; }
        public string HTMLText { get; set; }
        public string HTTP { get; set; }
        public string Here { get; set; }
        public string HLRLookupResult { get; set; }
        public string HLRSingleNumberLookup { get; set; }
        public string Id { get; set; }
        public string ImportContacts { get; set; }
        public string IMSI { get; set; }
        public string Incsvortxtfileseachcolumnshouldbeseparatedbyacomma { get; set; }
        public string InboxView { get; set; }
        public string Individual { get; set; }
        public string Import { get; set; }
        public string ImportDNDNumbers { get; set; }
        public string ImportFilterWords { get; set; }
        public string ImportFrom { get; set; }
        public string Inactive { get; set; }
        public string Inbox { get; set; }
        public string Informationfailed { get; set; }
        public string InformationSavedSuccessfully { get; set; }
        public string InformationUpdatedSuccessfully { get; set; }
        public string InProgress { get; set; }
        public string InsertError { get; set; }
        public string Instance { get; set; }
        public string InsufficentCredits { get; set; }
        public string InsufficentCreditstoTransfer { get; set; }
        public string InsufficientCredits { get; set; }
        public string Interval { get; set; }
        public string IntervalTimings { get; set; }
        public string Invalidcountriesselection { get; set; }
        public string Invalidcurrentpassword { get; set; }
        public string InvalidFileFormat { get; set; }
        public string Invalidfileformatforselectedfile { get; set; }
        public string Invalidinputdetails { get; set; }
        public string Invalidmobilefield { get; set; }
        public string InValidNos { get; set; }
        public string Invalidpassword { get; set; }
        public string Invalidrequest { get; set; }
        public string InvalidrequestMaximumCapitalCharactersreachedItshouldbe { get; set; }
        public string InvalidrequestMaximumPasswordLengthShouldbe { get; set; }
        public string InvalidrequestMinimumDigitscountnotmatchedItshouldbe { get; set; }
        public string InvalidrequestMinimumPasswordLengthShouldbe { get; set; }
        public string InvalidrequestNeedtoIncludeCapitalCharacters { get; set; }
        public string InvalidrequestNeedtoIncludeLowerCharacters { get; set; }
        public string InvalidrequestNeedtoIncludedigits { get; set; }
        public string InvalidrequestNeedtoIncludeSpecialcharacters { get; set; }
        public string InvalidrequestNeedtoIncludeSpecialwords { get; set; }
        public string InvalidrequestOldPasswordandNewPasswordShouldnotsame { get; set; }
        public string InvalidrequestspecialcharactersDoesntMatch { get; set; }
        public string InvalidSchedule { get; set; }
        public string InvalidScheduleTime { get; set; }
        public string InvalidTime { get; set; }
        public string INVALIMOBILENOs { get; set; }
        public string Invlaidpasswordpattren { get; set; }
        public string IPAddress { get; set; }
        public string IPAddressalreadyexists { get; set; }
        public string IPAddressalreadyexistsNoofSessionsUpdated { get; set; }
        public string ISDCode { get; set; }
        public string ISDCodeShouldNotZero0 { get; set; }
        public string Job { get; set; }
        public string JobLeft { get; set; }
        public string JobLeftshouldnotbelessthantheDateofJoining { get; set; }
        public string JobType { get; set; }
        public string JoinDate { get; set; }
        public string KeywordConfigurationView { get; set; }
        public string KeepAlivePeriod { get; set; }
        public string Keyword { get; set; }
        public string KeywordalreadyexistedinDB { get; set; }
        public string Keywordcouldntallowspacebetweenthewords { get; set; }
        public string Keywordexistedindbwithgivenname { get; set; }
        public string KickOff { get; set; }
        public string Language { get; set; }
        public string LastName { get; set; }
        public string ListName { get; set; }
        public string LockDate { get; set; }
        public string LogCommunication { get; set; }
        public string Login { get; set; }
        public string LoginPage { get; set; }
        public string Logo { get; set; }
        public string Logout { get; set; }
        public string LockedDate { get; set; }
        public string LookUpResult { get; set; }
        public string MapSendersList { get; set; }
        public string MapSenderView { get; set; }
        public string Messagewithtag { get; set; }
        public string MessageCredits { get; set; }
        public string MessageDetails { get; set; }
        public string Milliseconds { get; set; }
        public string mobilenumbers { get; set; }
        public string MobilenumbersshouldbespecifiedinthesubjectlinewithcomaseparatorandSMSmessageshouldbespecifiedinthemailbody { get; set; }
        public string MobileNoDomain { get; set; }
        public string MobileNoGroupName { get; set; }
        public string MOCampaigns { get; set; }
        public string ModulePlugin { get; set; }
        public string MOMapShortCode { get; set; }
        public string MOMapShortCodeView { get; set; }
        public string Month { get; set; }
        public string MOShortCode { get; set; }
        public string MailAlreadyConfigured { get; set; }
        public string Mailbox { get; set; }
        public string MailServer { get; set; }
        public string MailServerSettings { get; set; }
        public string MapSender { get; set; }
        public string MaximumLength { get; set; }
        public string MaximumlengthnotallowedlessthanMinimumlength { get; set; }
        public string Maximumnumberofcontactsexceeded { get; set; }
        public string Message { get; set; }
        public string Messagecreditsshouldnotexceeds12credits { get; set; }
        public string MessageField { get; set; }
        public string MessagePreview { get; set; }
        public string Messagesoutgoingtime { get; set; }
        public string MessageStatistics { get; set; }
        public string Messagetag { get; set; }
        public string MilliSecounds { get; set; }
        public string MinimumCapitalAlphabets { get; set; }
        public string MinimumDigits { get; set; }
        public string MinimumLength { get; set; }
        public string Minutes { get; set; }
        public string MISReport { get; set; }
        public string Mns { get; set; }
        public string Mobile { get; set; }
        public string MobileLength { get; set; }
        public string MobileNo { get; set; }
        public string MobileNubmer { get; set; }
        public string MobileNumber { get; set; }
        public string MobileNumberField { get; set; }
        public string MobileNumbersareInvalid { get; set; }
        public string MobilityCentre { get; set; }
        public string MOCampaign { get; set; }
        public string MOCampaignDeactivatedSuccessfully { get; set; }
        public string MOCampaignPausedSuccessfully { get; set; }
        public string MOCampaignSuspendedSuccessfully { get; set; }
        public string Mode { get; set; }
        public string MODetailed { get; set; }
        public string MODetailedReport { get; set; }
        public string MOOperations { get; set; }
        public string More { get; set; }
        public string MOReports { get; set; }
        public string MOSummary { get; set; }
        public string MOSummaryReport { get; set; }
        public string MOSurvey { get; set; }
        public string MOSurveyReport { get; set; }
        public string MOSurveysubmittedsuccessfully { get; set; }
        public string msgExceptionErr { get; set; }
        public string MsgID { get; set; }
        public string MsgSubmitSuccess { get; set; }
        public string MSISDN { get; set; }
        public string MultipleUsers { get; set; }
        public string N { get; set; }
        public string Name { get; set; }
        public string NewPassword { get; set; }
        public string Next { get; set; }
        public string No { get; set; }
        public string Nodataavailableintable { get; set; }
        public string NoDataFound { get; set; }
        public string Nodatafoundinfile { get; set; }
        public string Nodatafoundwiththefile { get; set; }
        public string NonDefaultRouteCannotbesettoDefaultRoute { get; set; }
        public string noofalertsexceededforcustomer { get; set; }
        public string NoofContacts { get; set; }
        public string NoOfSessions { get; set; }
        public string NotAllowed { get; set; }
        public string NotAllowedMaximumAlphabetslength { get; set; }
        public string NotAllowedMobileNumberLengthShoulddifferent { get; set; }
        public string NotAllowedSameSeriesNotAllowed { get; set; }
        public string NotAllowedSenderalreadymapped { get; set; }
        public string NotAllowedSeriesisalreadybindedwithanotheroperator { get; set; }
        public string NotAllowedWithSeriesandWithoutSeriesCombinationNotAllowed { get; set; }
        public string Numberofoptions { get; set; }
        public string NumericMobileNumberShouldNumeric { get; set; }
        public string NumericSeriesShouldNumeric { get; set; }
        public string NofileSelected { get; set; }
        public string NoteMessageTagshouldcontainbothstarttagandendtagwithcommaseparator { get; set; }
        public string NotePleaseappendcountrycodebeforemobilenumbertovalidatecorrectly { get; set; }
        public string NotePleaseenterCommaseparatedmobilenumberswithoutspace { get; set; }
        public string NumberOfContacts { get; set; }
        public string OK { get; set; }
        public string OperatorView { get; set; }
        public string Order { get; set; }
        public string OldPassword { get; set; }
        public string Operator { get; set; }
        public string OperatorAddedSuccessfully { get; set; }
        public string OperatorName { get; set; }
        public string OperatornotAddedContactSystemAdmin { get; set; }
        public string OperatorNotAddedMobileLengthShouldbedifferentfromMultipleOperatorsonSameCountry { get; set; }
        public string OperatornotAddedOperator { get; set; }
        public string OperatorNotUpdatedMobileLengthShouldbedifferentfromMultipleOperatorsonSameCountry { get; set; }
        public string OperatornotUpdatedOperator { get; set; }
        public string Operators { get; set; }
        public string OperatorUpdatedSuccessfully { get; set; }
        public string OrderAlreadyExisted { get; set; }
        public string OriginatorMail { get; set; }
        public string Others { get; set; }
        public string OutboundSender { get; set; }
        public string Package { get; set; }
        public string PageRefreshingin { get; set; }
        public string Parameter { get; set; }
        public string ParameterAlreadyExisted { get; set; }
        public string Password { get; set; }
        public string Passwordandconfirmpasswordnotmatched { get; set; }
        public string PasswordChangedSuccessfullyPleaseLoginAgain { get; set; }
        public string PasswordChangeRules { get; set; }
        public string PasswordRepeat { get; set; }
        public string Period { get; set; }
        public string PermitCount { get; set; }
        public string PerSecound { get; set; }
        public string PhoneBook { get; set; }
        public string PhoneNo { get; set; }
        public string PhoneNumberBusiness { get; set; }
        public string PhoneNumberTechnical { get; set; }
        public string PlainText { get; set; }
        public string PleaseaddatleastoneIPAddress { get; set; }
        public string PleaseAddAtleastOneMapDetails { get; set; }
        public string Pleaseaddcountry { get; set; }
        public string PleaseChecktheCheckbox { get; set; }
        public string Pleasechoosecorrectlanguage { get; set; }
        public string PleaseEnterAddressDetails { get; set; }
        public string PleaseEnterAtleastoneRecipient { get; set; }
        public string PleaseEnterCampaignName { get; set; }
        public string PleaseEnterComponent { get; set; }
        public string PleaseEnterConfirmPassword { get; set; }
        public string PleaseEnterConnectionName { get; set; }
        public string PleaseEnterContactNumber { get; set; }
        public string PleaseEnterContactPersonName { get; set; }
        public string PleaseEnterCountry { get; set; }
        public string PleaseEnterCustomerName { get; set; }
        public string PleaseEnterDestinationEmail { get; set; }
        public string PleaseEnterEmail { get; set; }
        public string PleaseEnterEmailAddress { get; set; }
        public string PleaseEnterEmailFormat { get; set; }
        public string PleaseEnterEmailSubject { get; set; }
        public string PleaseEnterFilterword { get; set; }
        public string PleaseEnterFirstName { get; set; }
        public string PleaseEnterFromName { get; set; }
        public string PleaseEnterIPAddress { get; set; }
        public string PleaseEnterISDCode { get; set; }
        public string PleaseEnterJoinDate { get; set; }
        public string PleaseEnterKeyword { get; set; }
        public string PleaseEnterLastName { get; set; }
        public string PleaseEnterMailbox { get; set; }
        public string PleaseEnterMailServer { get; set; }
        public string PleaseEnterMessage { get; set; }
        public string PleaseEnterMobileNo { get; set; }
        public string PleaseEnterMobileNumber { get; set; }
        public string PleaseEnterNewPassword { get; set; }
        public string PleaseEnterNoofSession { get; set; }
        public string Pleaseenternumberwithcountrycodeex971 { get; set; }
        public string PleaseEnterOldPassword { get; set; }
        public string PleaseEnterParameter { get; set; }
        public string PleaseEnterPassword { get; set; }
        public string PleaseEnterPhoneNumber { get; set; }
        public string PleaseEnterPortNumber { get; set; }
        public string PleaseenterrecipientmobilenumbersalongwithcountrycodeEg9715097155 { get; set; }
        public string PleaseEnterRoleName { get; set; }
        public string PleaseEnterRouteName { get; set; }
        public string PleaseEnterSenderIdShortCode { get; set; }
        public string PleaseEnterServer { get; set; }
        public string PleaseEnterSMPPUser { get; set; }
        public string PleaseEnterSMSCName { get; set; }
        public string PleaseEnterSurveyName { get; set; }
        public string PleaseEnterThroughput { get; set; }
        public string PleaseEnterURL { get; set; }
        public string PleaseEnterUserName { get; set; }
        public string pleaseentervalidCustomer { get; set; }
        public string pleaseentervalidemail { get; set; }
        public string pleaseentervalidUser { get; set; }
        public string PleaseEnterWinner { get; set; }
        public string PleaseSelectaFiletoImport { get; set; }
        public string Pleaseselectanyoneformat { get; set; }
        public string Pleaseselectatleastonecampign { get; set; }
        public string PleaseSelectAtleastOneUserType { get; set; }
        public string PleaseselectavalidFTPpath { get; set; }
        public string PleaseSelectCampaign { get; set; }
        public string PleaseSelectCampaignStatus { get; set; }
        public string PleaseSelectCampaignType { get; set; }
        public string pleaseselectcontactsfile { get; set; }
        public string PleaseselectcorrectlanguageforErrorMessage { get; set; }
        public string PleaseselectcorrectlanguageforReplyMessage { get; set; }
        public string PleaseSelectCreditType { get; set; }
        public string PleaseSelectCustomer { get; set; }
        public string PleaseSelectDate { get; set; }
        public string PleaseSelectEncryptionType { get; set; }
        public string PleaseSelectFilterByRecords { get; set; }
        public string pleaseselectgroup { get; set; }
        public string PleaseSelectKeyword { get; set; }
        public string PleaseSelectMobilenNoFiled { get; set; }
        public string Pleaseselectoneormoreitemstodelete { get; set; }
        public string PleaseSelectPreferredRoute { get; set; }
        public string PleaseSelectRecipientDetails { get; set; }
        public string PleaseSelectRetryLimit { get; set; }
        public string PleaseSelectRole { get; set; }
        public string PleaseSelectSender { get; set; }
        public string PleaseEnterSenderId { get; set; }
        public string PleaseSelectShortcode { get; set; }
        public string PleaseSelectShortcodeType { get; set; }
        public string PleaseSelectsingleSMSCatthetimeofUpdatingaRoute { get; set; }
        public string PleaseSelectSMPPID { get; set; }
        public string PleaseSelectSMSC { get; set; }
        public string PleaseSelectTimeInterval { get; set; }
        public string PleaseselectTransactionType { get; set; }
        public string PleaseSelectUser { get; set; }
        public string PleaseSelectVendor { get; set; }
        public string PleaseSelectVendorName { get; set; }
        public string PleaseSelectVersion { get; set; }
        public string PleaseSelectWinnertype { get; set; }
        public string Pleaseselectxlsxlsxfile { get; set; }
        public string PleaseUploadtheValidFile { get; set; }
        public string Port { get; set; }
        public string PreferedRoute { get; set; }
        public string PreferredRoute { get; set; }
        public string PreferredRoutealreadyExists { get; set; }
        public string ProcessemailswhenSmtpToSMSserviceisdown { get; set; }
        public string ProcessingTime { get; set; }
        public string ProductlogoshouldbereplacedwithCustomerLogo { get; set; }
        public string Progress { get; set; }
        public string Protocol { get; set; }
        public string ProtocolVersion { get; set; }
        public string PasswordRules { get; set; }
        public string PerSecond { get; set; }
        public string PreferredRouteView { get; set; }
        public string Preview { get; set; }
        public string Proceed { get; set; }
        public string ProcessTime { get; set; }
        public string RateCardView { get; set; }
        // public string Recipients { get; set; }
        public string RecipientsFileshouldbeNotepadCSVXLSorXLSX { get; set; }
        public string Recommendedthatthefirstrowisheaderasshownbelow { get; set; }
        public string ReplaceWith { get; set; }
        public string Reply { get; set; }
        public string ReplyText { get; set; }
        public string ReplyType { get; set; }
        public string ReportFor { get; set; }
        public string ReportOnCreditsConsumed { get; set; }
        public string RequiredSMPPForward { get; set; }
        public string ResetPasswordView { get; set; }
        public string RetryAttempts { get; set; }
        public string RetryInterval { get; set; }
        public string RetryLimit { get; set; }
        public string RetryType { get; set; }
        public string RolePrivileges { get; set; }
        public string RouteMasterView { get; set; }
        public string RouteName { get; set; }
        public string Rate { get; set; }
        public string RateCard { get; set; }
        public string Ratecardalreadyexists { get; set; }
        public string ReceivedTime { get; set; }
        public string Receiver { get; set; }
        public string RecipientS { get; set; }
        public string RecipientType { get; set; }
        public string RecordnotSavedContactsystemAdmin { get; set; }
        public string RecordUpdated { get; set; }
        public string Remarks { get; set; }
        public string Replay { get; set; }
        public string ReplyMessage { get; set; }
        public string Reports { get; set; }
        public string RequiredMobileLength { get; set; }
        public string Reset { get; set; }
        public string ResetPassword { get; set; }
        public string Restart { get; set; }
        public string RetryLimitAttempts { get; set; }
        public string Role { get; set; }
        public string RoleAddedSuccessfully { get; set; }
        public string Rolealreadyexistedindb { get; set; }
        public string RoleCreation { get; set; }
        public string Roleexistedindbwithgivenname { get; set; }
        public string RoleName { get; set; }
        public string RoleNotAddedErrorinAddingRole { get; set; }
        public string RoleNotAddedRoleNameAlreadyExist { get; set; }
        public string RoleNotUpdatedErrorinUpdatingRole { get; set; }
        public string RoleNotUpdatedRoleNameAlreadyExist { get; set; }
        public string RolePrivilegesSetup { get; set; }
        public string RoleUpdatedSuccessfully { get; set; }
        public string Route { get; set; }
        public string Category { get; set; }
        public string PleaseselectCategory { get; set; }
        public string RouteMaster { get; set; }
        public string Routenameshouldnotbeempty { get; set; }
        public string Routesalreadyexistswiththisname { get; set; }
        public string Save { get; set; }
        public string Schduled { get; set; }
        public string SchduleDate { get; set; }
        public string Schedule { get; set; }
        public string ScheduleDate { get; set; }
        public string ScheduleLater { get; set; }
        public string ScheduleTime { get; set; }
        public string Scheduletimeshouldbegreaterthancurrentdatetime { get; set; }
        public string ScheduletimeshouldnotbeLessthancurrentDateTime { get; set; }
        public string Search { get; set; }
        public string Searchby { get; set; }
        public string SecoundPrize { get; set; }
        public string Secounds { get; set; }
        public string SecurityManagement { get; set; }
        public string Select { get; set; }
        public string SelectCustomerType { get; set; }
        public string SelectedCountryHasNoOperators { get; set; }
        public string SelectEmailTemplate { get; set; }
        public string SelectExcelFile { get; set; }
        public string SelectFile { get; set; }
        public string SelectInterval { get; set; }
        public string SelectMOCampaign { get; set; }
        public string SelectSheet { get; set; }
        public string SelectTextExcelFile { get; set; }
        public string SelecttheRoletoassignprivileges { get; set; }
        public string SelectViewByCustomer { get; set; }
        public string SendDate { get; set; }
        public string SenderID { get; set; }
        public string SenderIdAddedSuccessfully { get; set; }
        public string SenderIdShortCode { get; set; }
        public string SenderIDShortCodeAddedSuccessfully { get; set; }
        public string SenderIDShortCodeFailedtoAdd { get; set; }
        public string SenderIDShortCodeFailedtoAddContactyourSystemAdmin { get; set; }
        public string SenderIdUpdatedSuccessfully { get; set; }
        public string SenderIdwiseReport { get; set; }
        public string Sendertag { get; set; }
        public string SenderwiseReport { get; set; }
        public string SendNow { get; set; }
        public string SendSMSServicemaynotbeupandrunningMOSurveywillbesentoncetheservicestarts { get; set; }
        public string Series { get; set; }
        public string SeriesalreadyExists { get; set; }
        public string Server { get; set; }
        public string ServerTimeout { get; set; }
        public string Session { get; set; }
        public string ShortCode { get; set; }
        public string ShortCodeAnalytic { get; set; }
        public string ShortcodeType { get; set; }
        public string Show { get; set; }
        public string SimpleSMS { get; set; }
        public string SingleUser { get; set; }
        public string SMPP { get; set; }
        public string SMPPAccount { get; set; }
        public string SMPPID { get; set; }
        public string SMPPIPAllocation { get; set; }
        public string SMPPMaster { get; set; }
        public string SMPPURL { get; set; }
        public string SMPPuseralreadyexists { get; set; }
        public string SMPPVersion { get; set; }
        public string SMSC { get; set; }
        public string SMSCalreadyExists { get; set; }
        public string SMSCName { get; set; }
        public string SMSCSettings { get; set; }
        public string SMSMO { get; set; }
        public string SMSMT { get; set; }
        public string SMSSent { get; set; }
        public string SMSToEmail { get; set; }
        public string SMSTracking { get; set; }
        public string SMTP { get; set; }
        public string SorryYourtriggerlimit { get; set; }
        public string SourceAddress { get; set; }
        public string SourceNPI { get; set; }
        public string SourceTon { get; set; }
        public string SrvcError { get; set; }
        public string Stage { get; set; }
        public string Start { get; set; }
        public string StartDate { get; set; }
        public string Starttag { get; set; }
        public string Status { get; set; }
        public string SubKeyword { get; set; }
        public string SubKeywordAlreadyExisted { get; set; }
        public string SubmissionType { get; set; }
        public string Submissiontypemustsenderid { get; set; }
        public string SubmissiontypemustShortcode { get; set; }
        public string Submit { get; set; }
        public string SuccessfullUpdated { get; set; }
        public string SuccessfullySynapseUserCreated { get; set; }
        public string SuccessfullySynapseUserUpdated { get; set; }
        public string SuccessfullytoUpdateyourrequest { get; set; }
        public string Successfullyuploadedthefile { get; set; }
        public string SuccessResponse { get; set; }
        public string Summary { get; set; }
        public string Survey { get; set; }
        public string SurveyAnalytic { get; set; }
        public string SurveyEndDate { get; set; }
        public string Surveyexistedindbwithgivenname { get; set; }
        public string SurveyName { get; set; }
        public string SurveyQuestions { get; set; }
        public string SurveyStartDate { get; set; }
        public string Suspended { get; set; }
        public string SystemID { get; set; }
        public string SystemMode { get; set; }
        public string SystemType { get; set; }
        public string Seconds { get; set; }
        public string SelectGroupFile { get; set; }
        public string SelectGroups { get; set; }
        public string SenderIdwithtag { get; set; }
        public string senderIdwithtagMessagewithtag { get; set; }
        public string SenderIdShortcodeView { get; set; }
        //   public  string SenderWiseReport { get; set; }
        public string ServerType { get; set; }
        public string SimpleSMSPreview { get; set; }
        public string SMPPMasterView { get; set; }
        public string SMSType { get; set; }
        public string SMSMessage { get; set; }
        public string SMSMessages { get; set; }
        public string SMSPreview { get; set; }
        public string StatusRate { get; set; }
        public string Subject { get; set; }
        public string SynapseMISReport { get; set; }
        public string TagFormats { get; set; }
        public string Tags { get; set; }
        public string Template3 { get; set; }
        public string Template4 { get; set; }
        public string Template5 { get; set; }
        public string Template5A { get; set; }
        public string TemplateFormats { get; set; }
        public string TemplateMessageFields { get; set; }
        public string TestSMSCView { get; set; }
        public string Thankyou { get; set; }
        public string TimeInterval { get; set; }
        public string ToaddresscontainsmailboxsubjectlineshouldcontainmobilenumbersandbodyshouldcontainSMSmessagewithEndofMessaagetag { get; set; }
        public string ToaddresscontainsmobilenumbersasshownsubjectlinecanbeanyandbodyshouldcontainSMSmessagewithEndofMessaagetag { get; set; }
        public string ToaddressshouldcontainsmailboxMobilenumbersshouldbeinattachedfiletxtorcsvwithSMSmessageinbodytosendbulkSMS { get; set; }
        public string toaddSMPPIPDetails { get; set; }
        public string TotalCredits { get; set; }
        public string TotalCreditsUsed { get; set; }
        public string TriggerClientConfig { get; set; }
        public string TriggerGroupofXML { get; set; }
        public string TriggerServerConfig { get; set; }
        public string Tag { get; set; }
        public string Technical { get; set; }
        public string TechnicalEmail { get; set; }
        public string Template { get; set; }
        public string Template1 { get; set; }
        public string Template2 { get; set; }
        public string TemplatealreadyexistedinDB { get; set; }
        public string Templateexistedindbwithgivenname { get; set; }
        public string Test { get; set; }
        public string TestSMSC { get; set; }
        public string TestSMSsubmittedsuccessfully { get; set; }
        public string ThiscustomerbelongsanotheraccountmanagerDoyouwantproceed { get; set; }
        public string TimeIntervalSeconds { get; set; }
        public string To { get; set; }
        public string ToDate { get; set; }
        public string TotalCount { get; set; }
        public string TotalCreadits { get; set; }
        public string TPS { get; set; }
        public string TransactionalCampaigns { get; set; }
        public string TransactionCredits { get; set; }
        public string TransactionCreditsshouldnotbeempty { get; set; }
        public string TransactioncreditsShouldnotbemorethanCurrentBalanceforRollbackType { get; set; }
        public string TransactioncreditsShouldnotbezero { get; set; }
        public string TransactionType { get; set; }
        public string Transciever { get; set; }
        public string Transmitter { get; set; }
        public string UnableProcessPleasecontactadmin { get; set; }
        public string Unbind { get; set; }
        public string UnLockUser { get; set; }
        public string UpdatedSuccessfully { get; set; }
        public string UpdateError { get; set; }
        public string UpdatingfailedtoCustomerCustomernotexistedindb { get; set; }
        public string Updatingfailedtoinformation { get; set; }
        public string UploadCSVTextFileforMultipleNumberLookup { get; set; }
        public string UploadedfiledoesthavingmatchedcountrycodesforselectedsenderID { get; set; }
        public string Uploadfile { get; set; }
        public string UploadFileshouldcontainheaderinformation { get; set; }
        public string URL { get; set; }
        public string URLTemplateText { get; set; }
        public string URLTemplateUnicode { get; set; }
        public string User { get; set; }
        public string Useralreadyexistedindb { get; set; }
        public string UserCreation { get; set; }
        public string UserisalreadymappedwithaGenericSenderID { get; set; }
        public string UserisalreadymappedwithaOpenSenderIDANY { get; set; }
        public string UserManagement { get; set; }
        public string UserName { get; set; }
        public string UserNameAlreadyExisted { get; set; }
        public string Users { get; set; }
        public string UnlockUserView { get; set; }
        public string UserView { get; set; }
        public string ValidFrom { get; set; }
        public string ValidTo { get; set; }
        public string VendorMasterView { get; set; }
        public string ValidityPeriodDays { get; set; }
        public string Validpassword { get; set; }
        public string ValidRecipients { get; set; }
        public string Value { get; set; }
        public string ValueAlreadyExisted { get; set; }
        public string Vendor { get; set; }
        public string VendordetailsnotaddedContactSystemAdmin { get; set; }
        public string VendorMaster { get; set; }
        public string VendorName { get; set; }
        public string Vendornamealreadyexisted { get; set; }
        public string VendorView { get; set; }
        public string WEB { get; set; }
        public string Winner { get; set; }
        public string WinnerReport { get; set; }
        public string Winners { get; set; }
        public string WinnerType { get; set; }
        public string WinnersCampaign { get; set; }
        public string WinnersList { get; set; }
        public string WinnersReport { get; set; }
        public string XMLGenaration { get; set; }
        public string Year { get; set; }
        public string YourTestSMSChasbeensubmittedsuccessfully { get; set; }
        public string YourSurveyhasbeensubmitedsuccessfully { get; set; }
        public string Y { get; set; }
        public string Yes { get; set; }
        public string YoucannotedittheCampaignthekickofftimewascompleted { get; set; }
        public string Youcantdoanyoperationwiththeselectedcampaign { get; set; }
        public string Yourapplicationdescriptionpage { get; set; }
        public string Yourcontactpage { get; set; }
        public string YouwillreceiveonEmailonceLookupProccessiscompleted { get; set; }
        public string NofileSelectedChooseFile { get; set; }
        public string NoteForDynamicSenderIDchooseSenderIDasANYApplicableonlyforSMPP { get; set; }

        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string Addauser { get; set; }
        public string UserType { get; set; }
        public string AddAccountManager { get; set; }
        public string AccountManagers { get; set; }
        public string AddRole { get; set; }
        public string Roles { get; set; }
        public string RoleView { get; set; }
        public string Feature { get; set; }
        public string XMLTrigger { get; set; }
        public string Sessions { get; set; }
        public string CampaignSummaryReportbetween { get; set; }
        public string SubCustomer { get; set; }
        public string SentDate { get; set; }
        public string toaddRoute { get; set; }
        public string SMSCMaster { get; set; }
        public string AddOperator { get; set; }
        public string AddCountry { get; set; }
        public string toaddmobilelength { get; set; }
        public string SuccessRecords { get; set; }
        public string CountryName { get; set; }
        public string TechnicalPhone { get; set; }
        public string BusinessPhone { get; set; }



        public string Failedtosavetheinformation { get; set; }


        public string pleaseselectmobilenumbers { get; set; }
        public string InvalidFile { get; set; }


        public string Checked { get; set; }
        public string Invalid { get; set; }
        public string SurveyNamealreadyExists { get; set; }
        public string FilenotExist { get; set; }
        public string Messagesubmittedsuccessfully { get; set; }

        public string MailServeralreadyconfigured { get; set; }
        public string CannotChangeMailServerDetailsAlreadyConfigured { get; set; }
        public string InvalidCredentialsPort { get; set; }
        public string MailServeralreadyexisted { get; set; }
        public string Fromemailalreadyconfiguredchooseanotherfrommail { get; set; }
        public string Campaignalreadyexisted { get; set; }
        public string PleaseenterTemplate { get; set; }
        public string SenderMessageTagsareShouldnotbesame { get; set; }
        public string SenderTagInvalidFormatExFormat { get; set; }
        public string MessageTagInvalidFormatExFormat { get; set; }
        public string Pleaseenteronlynumbers { get; set; }
        public string DuplicateMobilenumbersfound { get; set; }
        public string MobileNumberdoesnthavingmatchedcountrycodesforselectedsenderID { get; set; }
        public string SendSMSServicemaynotbeupandrunningMessageswillbesentoncetheservicestarts { get; set; }
        public string Areyousureyouwanttopermanetlydeletethisfile { get; set; }
        public string SynapseCampaignswillnotbesendatthistimeslot { get; set; }
        public string ScheduletimeshouldbegreatherthancurrentdatetimeincludingPreProcessTime { get; set; }
        public string CampaignNamealreadyExists { get; set; }
        public string Campaignsubmittedsuccessfully { get; set; }
        public string SendSMSServicemaynotbeupandrunningCampaignwillbesentoncetheservicestarts { get; set; }
        public string pleaseselectmobilenumberfield { get; set; }
        public string pleaseselectSheet { get; set; }
        public string pleaseselectfile { get; set; }
        public string Countshouldnotbezero { get; set; }
        public string Filedeletedbysomeone { get; set; }
        public string Pleaseselectonecampignonly { get; set; }
        public string InvalidrequestMinimumCapitalCharactersreachedItshouldbe { get; set; }
        public string InvalidrequestMinimumCapitalCharactersnotmatchedItshouldbe { get; set; }
        public string Pleaseenteronly { get; set; }
        public string CampaignNameAlreadyExisted { get; set; }
        public string pleaseselectMsgID { get; set; }
        public string pleaseselectMSISDN { get; set; }
        public string SurveyReports { get; set; }
        public string Filenotfound { get; set; }
        public string PleasemapatleastoneCustommessagefield { get; set; }
        public string pleaseselectGroups { get; set; }
        public string PleaseEnterStartDate { get; set; }
        public string PleaseEnterEndDate { get; set; }

        public string PleaseSelectthedates { get; set; }
        public string Originator { get; set; }
        public string ResetForm { get; set; }
        public string Back { get; set; }
        public string Count { get; set; }
        public string Percentage { get; set; }
        public string Daysmustbelessthan31 { get; set; }
        public string pleaseselectTextExcelfile { get; set; }
        public string pleaseSelectMobileNoField { get; set; }
        public string pleaseselectHours { get; set; }
        public string pleaseselectminutes { get; set; }
        public string PleaseEnterTemplatename { get; set; }
        public string SelectCustomer { get; set; }
        public string PleaseEnterfromemail { get; set; }
        public string PleaseEnterDomain { get; set; }
        public string PleaseEnterSenderTag { get; set; }
        public string PleaseEnterMessageTag { get; set; }
        public string PleaseEnterStartTag { get; set; }
        public string PleaseEnterEndTag { get; set; }
        public string PleaseEnterCCemail { get; set; }
        public string PleaseSelectSubKeyword { get; set; }
        public string PleaseSelectOutboundSender { get; set; }
        public string PleaseEnterDate { get; set; }
        public string PleaseenterReplyMessage { get; set; }
        public string PleaseenterErrorMessage { get; set; }
        public string PleaseenterSetTime { get; set; }
        public string PleaseenterValue { get; set; }
        public string PleaseEnterRetryLimitAttempts { get; set; }
        public string PleaseEnterTimeIntervalSeconds { get; set; }
        public string PleaseenterQuestion { get; set; }
        public string PleaseenterFooter { get; set; }
        public string pleaseSelectMOCampaign { get; set; }
        public string pleaseentercommaseperatedmobileNos { get; set; }
        public string PleaseEnterWinners { get; set; }
        public string Maximumrecipientsare { get; set; }




        public string Showing0to0of0entries { get; set; }
        public string ComposeBulkSMS { get; set; }
        public string TestSMS { get; set; }
        public string ReceivedDate { get; set; }

        public string TotalFileCount { get; set; }
        public string TotalCreditsRequired { get; set; }
        public string ValidateCount { get; set; }
        public string CreditsPerMessage { get; set; }
        public string AllowDuplicateMobileNumbers { get; set; }
        public string NameOrRecipients { get; set; }
        public string TotalSMSSent { get; set; }
        public string Last15minutes { get; set; }
        public string Last30minutes { get; set; }
        public string Last60minutes { get; set; }

        //  public string MOMapShortCode { get; set; }
        public string ProfileCreation { get; set; }
        public string BusinessRules { get; set; }
        public string TemplateCreation { get; set; }
        public string OnlineAlerts { get; set; }
        public string OfflineAlerts { get; set; }
        public string Pleseentermorethan3characters { get; set; }
        public string Invalidgroupscount { get; set; }
        public string Invalidcontactscount { get; set; }
        public string Failedtosavethefile { get; set; }
        public string Areyousurestoptheprocess { get; set; }
        public string Newpasswordconfimpassworddoesmatch { get; set; }
        public string Createdsuccessfully { get; set; }
        public string selectedfileformatisinvalid { get; set; }
        public string Pleaseentername { get; set; }
        public string Pleaseselectformat { get; set; }
        //  public string pleaseselectfile { get; set; }
        public string pleaseselectFilterword { get; set; }
        public string pleaseselectReplaceWith { get; set; }
        public string Pleaseenterdescription { get; set; }
        public string PleaseSelectPasswordMinimumLength { get; set; }
        public string PleaseSelectMaximumLength { get; set; }
        public string PleaseSelectMinimumNumberofCapitalAlphabets { get; set; }
        public string PleaseSelectMinimumNumberofDigits { get; set; }
        public string PleaseSelectDayslefttoExpiry { get; set; }
        public string PleaseSelectPasswordRepeat { get; set; }
        public string PleaseSelectAllowedSpecialCharacters { get; set; }
        public string PleaseSelectChangePasswordonFirstLogin { get; set; }
        public string PleaseSelectRoleFeatures { get; set; }
        public string Pleaseenterenquiryintervaltime { get; set; }
        public string Pleaseselectroute { get; set; }
        public string PleaseselectDispatchSenderId { get; set; }
        public string DispatchedSID { get; set; }
        public string PleaseselectDisplayShortCode { get; set; }
        // public string AlreadyexistedinMOCampaing { get; set; }
        public string PleaseselectCountry { get; set; }
        public string PleaseselectOperator { get; set; }
        public string PleaseenterMobileLength { get; set; }
        public string PleaseAddAtleastOneOperator { get; set; }
        public string NotallowedDefaultRoutealreadyMappedforselectedPrefferredroute { get; set; }
        public string Nondefaultroutedoesntexistsselectedcountry { get; set; }
        public string pleaseselectRate { get; set; }
        public string pleaseselectCurrency { get; set; }
        public string PleaseselectSenderType { get; set; }
        public string PleaseselectMOShortCode { get; set; }
        public string NotAllowedDataExisted { get; set; }
        public string MappingexistsinRouteMasterPleasedeactivaterouteandthenActivateDeactivateEditSMSC { get; set; }
        public string PleaseSelectProtocol { get; set; }
        public string PleaseEnterSystemID { get; set; }
        public string PleaseEnterServerName { get; set; }
        public string PleaseEnterURLTemplate { get; set; }
        public string PleaseEnterURLTemplateUnicode { get; set; }
        public string PleaseEnterSuccessResponse { get; set; }
        public string PleaseEnterErrorResponse { get; set; }
        public string SessionCountExceeded { get; set; }
        public string PleaseSelectinstance { get; set; }
        public string MoreDetails { get; set; }
        public string Pleaseselectautoconn { get; set; }
        public string Pleaseselectlogon { get; set; }
        public string PleaseselectDLR { get; set; }
        public string Pleaseselectprotocolversion { get; set; }
        public string Pleaseselectcharset { get; set; }
        public string PleaseselectDCSValue { get; set; }
        public string PleaseselectDestNpi { get; set; }
        public string PleaseselectSourceTon { get; set; }
        public string PleaseselectSourceNpi { get; set; }
        public string PleaseEnterSourceaddress { get; set; }
        public string Areyousureyouwanttoproceedtofurther { get; set; }
        public string youcannotuseatthefirstorlastcharacteroftextbox { get; set; }
        public string MappingexistsinRouteMasterPleasedeactivatetheSMSC { get; set; }
        public string pleaseselectcountryandoperator { get; set; }
        public string pleaseaddatleastoneroute { get; set; }
        public string Success { get; set; }
        public string Invalidsubmit { get; set; }
        public string MoShortCodeAddedSuccessfully { get; set; }
        public string MoShortCodeFailedtoAdd { get; set; }
        public string MoShortCodeFailedtoAddContactyourSystemAdmin { get; set; }
        public string TestUser1 { get; set; }
        public string TestUser2 { get; set; }
        public string TestUser3 { get; set; }
        public string ForxlsxlsxthesheetnamemustbeSheet1 { get; set; }
        public string DNDNotepadFileShouldbeinthisFormat { get; set; }

        public string FilterWordsFileShouldbeinthisFormat { get; set; }
        public string ForxlsxlsxsheetDatashouldbeatSheet1 { get; set; }
        public string Yourcustomercreationhasbeensubmittedsuccessfully { get; set; }
        public string AreYousurewanttochangethestatus { get; set; }
        public string MobileNumberpatternisdefaultCountryCodeNumber971 { get; set; }
        public string Mobilenumberpatternis971 { get; set; }
        public string Mobilenumberpatternis00971 { get; set; }
        public string CountrycodeneedstobeappendedtoMobilenumberforEx971 { get; set; }
        public string Mobilenumberpatternis0971 { get; set; }
        public string PleaseEnterBusinessRuleValue { get; set; }
        public string BusinessRule { get; set; }
        public string SelectProfile { get; set; }
        public string PleaseselectProfile { get; set; }
        public string PleaseenterFileSeparator { get; set; }
        public string FileSeparator { get; set; }
        public string FilePath { get; set; }
        public string PleaseenterFilePath { get; set; }
        public string UpdateValue { get; set; }
        public string PleaseEnterUpdateValue { get; set; }
        public string SelectStatement { get; set; }
        public string PleaseenterSelectStatement { get; set; }
        public string StatusUpdateIsRequired { get; set; }
        public string PleaseEnterSelectTable { get; set; }
        public string HintEnteraliasnamewithseparatorExUniqyID { get; set; }
        public string StatusColumn { get; set; }
        public string PleaseEnterUniqueIDColumn { get; set; }
        public string TestResult { get; set; }
        public string BusinessRuleView { get; set; }
        public string UniqueIDColumn { get; set; }

        public string CreateProfile { get; set; }
        public string ProfileName { get; set; }
        public string Pleaseenterprofilename { get; set; }
        public string DBType { get; set; }
        public string HostIPAddress { get; set; }
        public string PleaseselectdBtype { get; set; }


        //  public string PleaseEnterPassword { get; set; }
        public string pleaseenterport { get; set; }
        public string ServiceName { get; set; }


        public string Profiles { get; set; }
        //   public string Test { get; set; }
        public string ProfileCreationView { get; set; }
        public string Connectionestablishedsuccessfully { get; set; }
        public string InvalidServerCredentialsPleasetryagain { get; set; }
        public string OracleConnectionnotestablishedRequiresOracleclientsoftwareversionorgreater { get; set; }
        public string SqlConnectionnotestablishedTheserverwasnotfoundorwasnotaccessible { get; set; }
        public string SqlConnectionnotestablishedInvalidHOST { get; set; }
        public string SqlConnectionnotestablishedLoginFailforincorrectusernameandpassword { get; set; }
        public string ProfilealreadyExists { get; set; }



        public string Pleasedeactivatethealertfirstandmakethenecessarychanges { get; set; }
        public string DatabaseName { get; set; }
        public string PleaseselectDatabaseName { get; set; }
        public string PleaseselectServiceName { get; set; }
        public string AlertName { get; set; }
        public string MessageTemplate { get; set; }
        public string MessageFiled { get; set; }
        public string pleaseentermobilenumberalongwithcountrycode { get; set; }
        public string SearchGroup { get; set; }
        public string SetTime { get; set; }
        public string UserDisplay { get; set; }
        public string Previous { get; set; }
        public string Pleaseactivatekeywordinkeywordpage { get; set; }
        public string CampaignalreadymappedinSMSTOEMAIL { get; set; }
        public string Campaignnameshouldntbeempty { get; set; }
        public string AreyousurewanttoremoveSubKeywords { get; set; }
        public string SelectSubKeyword { get; set; }
        public string SelectSMPPUser { get; set; }
        public string SelectSender { get; set; }
        public string SelectShortcode { get; set; }
        public string SelectUser { get; set; }

        public string AlreadyExisted { get; set; }
        public string SelectCustomeri { get; set; }
        public string EnterShortcode { get; set; }
        public string EnterKeyword { get; set; }
        public string Standard { get; set; }
        public string FromName { get; set; }


        public string NotePleaseenterseperatedformultipleemails { get; set; }
        // public string FromEmail { get; set; }
        public string Exvectramindcom { get; set; }

        public string NoteSenderTagshouldcontainbothstarttagandendtagwithcommaseparator { get; set; }
        public string Notearenotallowed { get; set; }



        public string Inputmailboxtoread { get; set; }
        public string Inputmailserver { get; set; }
        public string InputPortNumber { get; set; }


        public string EnterMobileNumbers { get; set; }



        public string EnterMessage { get; set; }
        public string AllowDuplicates { get; set; }

        public string PleasechoosecorrectlanguageforDescriptionMessage { get; set; }
        public string Yearwisestatistics { get; set; }
        public string Monthwisestatistics { get; set; }
        public string Campaignwisestatistics { get; set; }
        public string Daywisestatistics { get; set; }
        public string D { get; set; }
        public string W { get; set; }
        public string M { get; set; }

        public string MobileField { get; set; }
        public string EmailField { get; set; }


        public string IsDLRRequired { get; set; }
        public string IsResponseEmailRequired { get; set; }
        public string ScheduleInterval { get; set; }
        public string IntervalType { get; set; }
        public string EveryHour { get; set; }
        public string EveryMinute { get; set; }
        public string EverySecond { get; set; }
        public string EveryDay { get; set; }
        public string DayofWeek { get; set; }
        public string Time { get; set; }
        public string Onlinealertsavedsuccessfully { get; set; }
        public string Onlinealertalreadyexists { get; set; }
        public string MapColumns { get; set; }
        public string CustomColumn { get; set; }
        public string ColumnList { get; set; }
        public string Type { get; set; }
        public string Text { get; set; }
        public string Verify { get; set; }
        public string TemplateInformationVerified { get; set; }
        public string TemplateareadyExists { get; set; }
        public string Pleaseenteralteastonecustomcolumn { get; set; }
        public string DuplicateColumnPleasetryagain { get; set; }

        public string ResponseEmailAddressTo { get; set; }
        public string PleaseselectUserType { get; set; }
        public string PleaseSelectBusinessRule { get; set; }
        public string ServerInstance { get; set; }
        public string PleaseSelectServerInstance { get; set; }
        public string ResponseEmailAddressBCC { get; set; }
        public string ResponseEmailAddressCC { get; set; }
        public string pleaseSelectServer { get; set; }
        public string PleaseEnterCCEmailAddress { get; set; }
        public string PleaseEnterBCCEmailAddress { get; set; }
        public string Offlinealertssavedsuccessfully { get; set; }
        public string Offlinealertalreadyexists { get; set; }
        public string Pleaseentercolumns { get; set; }
        public string PleaseenterMessagefields { get; set; }
        public string Arabic { get; set; }
        public string English { get; set; }
        public string PleaseenterTextArea { get; set; }
        public string SelectBusinessRule { get; set; }
        public string SelectAccountManager { get; set; }
        public string PermittoCreateCount { get; set; }

        public string FullAddress { get; set; }
        public string SearchonMobileNumberorResponse { get; set; }
        public string Exportto { get; set; }
        public string SelectSurvey { get; set; }
        public string SearchCountry { get; set; }
        public string DatabaseSearch { get; set; }



        public string SelectCountry { get; set; }
        public string SelectVendorName { get; set; }
        public string SelectRoute { get; set; }

        public string Alreadymappingexisted { get; set; }
        public string SelectVendor { get; set; }


        public string SuccessfullycustomerUpdated { get; set; }
        public string SuccessfullycustomerCreated { get; set; }
        public string Customeralreadyexistedindbwithgivenname { get; set; }


        public string Userdoesntexistedinactivedirectory { get; set; }

        public string Accounthasbeenlockedpleasetryaftersometime { get; set; }
        public string Networkissuepleasecontactsystemadmin { get; set; }
        public string IncompleteconfigurationPleasecontactadmin { get; set; }
        public string Customerexpiredpleasecontactadmin { get; set; }
        public string duetootheryouraccountlockedpleasecontactsystemadmin { get; set; }
        public string UserSessionExceeded { get; set; }
        public string CustomerNotApprovedInactivated { get; set; }
        public string UserNotAuthorizedtoAccessWebApp { get; set; }
        public string Invalidloginattempt { get; set; }
        public string Invalidcode { get; set; }
        public string YourpasswordhasbeenresetPlease { get; set; }

        public string Pleasecheckyouremailtoresetyourpassword { get; set; }
        public string EmailLink { get; set; }
        public string Unsuccessfulloginwithservice { get; set; }
        public string Youvesuccessfullyauthenticatedwith { get; set; }
        public string PleaseenterausernameforthissitebelowandclicktheRegisterbuttontofinishloggingin { get; set; }
        public string EnterYourEmail { get; set; }
        public string Pleaseenteryouremail { get; set; }
        //public string Username { get; set; }
        public string ThankyouforconfirmingyouremailPlease { get; set; }


        public string DaysLefttoExpiry { get; set; }
        public string UserDashboard { get; set; }
        public string ModuleWiseLoadLast48hours { get; set; }
        public string DateWiseLoadLast48hours { get; set; }
        public string NoDataWiseLoad { get; set; }
        public string SenderWiseLoadLast48hours { get; set; }
        public string NoSenderIdWiseLoad { get; set; }
        public string DEMOSYNAPSE { get; set; }
        public string CustomerDetails { get; set; }
        public string VECTRAMIND { get; set; }
        public string ExpiryDate { get; set; }
        public string ENTERPRISE { get; set; }
        public string CreditSystem { get; set; }
        public string POSTPAID { get; set; }
        public string NoofCreditsAvailable { get; set; }
        public string UNLIMITED { get; set; }
        public string Routes { get; set; }
        public string UNITEDARABEMIRATES971 { get; set; }
        public string SynapseApplication { get; set; }
        public string BalanceCredits { get; set; }
        public string VectramindCorporation { get; set; }

        public string Location { get; set; }
        public string Thisistheitemdescription { get; set; }
        public string Security { get; set; }
        public string Support { get; set; }
        public string DataBackup { get; set; }
        public string Hot { get; set; }
        public string ScreenLock { get; set; }
        public string FAQ { get; set; }
        public string SearchResult { get; set; }
        public string Pages { get; set; }

        public string Lockedout { get; set; }
        public string RecentActivities { get; set; }


        public string CampaignDetails { get; set; }
        public string NoPrivileges { get; set; }
        public string DetailAnalysis { get; set; }
        public string AnotherDefaultRouteinactivestatePreferedRoute { get; set; }
        public string Firstcharactershouldnotbe0 { get; set; }
        public string Messagelanguagedidnotmatchwiththeselectedlanguage { get; set; }
        public string Specialcharactersarenotallowed { get; set; }
        public string AreyousureactiverecordAreyousureinactiverecord { get; set; }

        public string PreProcessIntervalTime { get; set; }
        public string OnpreprocessorRestart { get; set; }
        public string SuspendAllCampaignsIncludingTodays { get; set; }
        public string EditAuditLogs { get; set; }
        public string AuditLogView { get; set; }
        public string PageName { get; set; }


        public string CreatedOn { get; set; }
        public string Division { get; set; }
        public string AddMapDivision { get; set; }
        public string MapDivision { get; set; }
        public string Choosefile { get; set; }
        public string MailServerSettingsView { get; set; }
        public string EmailToSMSView { get; set; }
        public string SMSToEmailView { get; set; }
        public string ÈmailTemplateView { get; set; }
        public string EmailType { get; set; }
        public string NoneSelected { get; set; }
        public string APIIPWhitelist { get; set; }
        public string ANYIPAddress { get; set; }
        public string APIIPWhitelistView { get; set; }
        public string POP3 { get; set; }
        public string Anerroroccurredwhileprocessingyourrequest { get; set; }
        public string Thisaccounthasbeenlockedoutpleasetryagainlater { get; set; }
        public string Logoff { get; set; }
        public string SelectCampaignType { get; set; }

        public string AutoConection { get; set; }

        //  public string NameOrRecipients { get; set; }
        public string DelieveryReport { get; set; }
        public string DatabaseType { get; set; }
        public string ServerName { get; set; }
        public string DefaultDB { get; set; }
        public string ConfiguredRules { get; set; }
        public string Online { get; set; }
        public string Offline { get; set; }
        public string CountryCode { get; set; }
        public string SelectTable { get; set; }
        public string Choose { get; set; }
        public string PleaseEnterAlertName { get; set; }
        public string ViewLog { get; set; }
        public string PleaseEnterCountrycode { get; set; }
        public string PleaseEnterStatusColumn { get; set; }
        public string FailedtoDbConnectionsandStatement { get; set; }
        public string Successfully { get; set; }
        public string PleaseEnterValidSelectStatement { get; set; }
        public string Pleaseselectvalidcolumn { get; set; }
        public string PleaseEnterValidSelectStatementandProfile { get; set; }
        public string BusinessRulealreadyexists { get; set; }
        public string PleaseEnterthevalidstatement { get; set; }
        public string PleaseEnterthevalidupdatetableandUniquecolumnandstatuscolumn { get; set; }
        public string PleaseEnterthevalidupdatetable { get; set; }
        public string InvalidKeysfoundintheselectstatement { get; set; }
        public string PleaseEnterthevalidUniqueandstatuscolumn { get; set; }
        public string Nosuchhostisknown { get; set; }
        public string Thewaitoperationtimedout { get; set; }
        public string Loginfailedforuser { get; set; }
        public string Invalidkeyfoundinselectstatement { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public string Updated { get; set; }
        public string Last { get; set; }

        public string Created { get; set; }
        public string AssembleLongMessages { get; set; }
        public string PleaseatleastaddoneSystemMode { get; set; }
        public string SeriesNotFound { get; set; }
        public string PleaseEnterMoShortCode { get; set; }
        public string Alreadyexistedwithuser { get; set; }
        public string SelectMailbox { get; set; }
        public string PleaseSelectAtleastOneFormat { get; set; }
        public string DestinationMail { get; set; }
        public string CCMail { get; set; }
        public string Templatenameshouldnotbeempty { get; set; }
        public string BindStatus { get; set; }
        public string yoursessionhasbeenexpired { get; set; }
        public string Accepted { get; set; }
        public string pleaseEnterGroupName { get; set; }
        public string WinnersView { get; set; }
        public string ComposeSimpleSMS { get; set; }
        public string Forwardview { get; set; }
        public string Templates { get; set; }
        public string PleaseselectTemplate { get; set; }

        public string BulkSMSView { get; set; }
        public string Submitted { get; set; }
        public string Delivered { get; set; }
        public string CustomerUserWise { get; set; }
        public string CountrySenderWise { get; set; }
        public string CustomerWise { get; set; }
        public string UserWise { get; set; }
        public string SenderWise { get; set; }
        public string RouteWise { get; set; }
        public string RuleType { get; set; }
        public string CreateBusinessRules { get; set; }
        public string InvalidFileMobileColumnShouldnotbeempty { get; set; }
        public string IPAddressalreadyexisted { get; set; }
        public string SaveMappings { get; set; }
        public string MessageFields { get; set; }
        public string MapCustomColumns { get; set; }
        public string UseTemplate { get; set; }
        public string ComposeCustomSMS { get; set; }
        public string SelectMobileNumberField { get; set; }
        public string SelectMessageField { get; set; }
        public string SelectSenderID { get; set; }
        public string HttpURL { get; set; }
        public string Premium { get; set; }
        public string NonPremium { get; set; }
        public string PleaseEnterDestination { get; set; }
        public string OtherParameter { get; set; }
        public string ForwaredDate { get; set; }
        public string SelectCustomers { get; set; }
        public string SelectRole { get; set; }
        public string CampaignisInactiveyoucantactivatedthisrecord { get; set; }
        public string Keywords { get; set; }
        public string FormatsTemplate { get; set; }
        public string TemplateView { get; set; }
        public string PleaseEnterdatainCustomcolumn { get; set; }
        public string WinnerSettingsName { get; set; }
        public string WinnersSelectionStartDate { get; set; }
        public string WinnersSelectionEndDate { get; set; }
        public string NoofWinners { get; set; }
        public string NoofConsolation { get; set; }
        public string CustomSMSView { get; set; }
        public string SimpleSMSView { get; set; }
        public string MOSurveyView { get; set; }
        public string SurveyAnalytics { get; set; }
        public string TotalSMS { get; set; }
        public string AlreadyexistedinMOCampaign { get; set; }


        public string PleaseSelectOriginator { get; set; }
        public string PleaseSelectStatus { get; set; }
        public string PleaseSelectStartDate { get; set; }
        public string PleaseSelectEndDate { get; set; }
        public string PleaseEnterWinnerName { get; set; }
        public string PleaseSelectWinnerSettingsName { get; set; }
        public string WinnerSettingName { get; set; }
        public string WinnerStartDate { get; set; }
        public string YouhaveenteredaninvalidIPaddress { get; set; }
        public string AddatleastoneIP { get; set; }
        public string DNDExcelFileShouldbeinthisFormat { get; set; }
        public string TotalSMSPushed { get; set; }
        public string pleaseselectmonth { get; set; }
        public string ScheduleOn { get; set; }
        public string Valid { get; set; }
        public string Sender { get; set; }
        public string DayTotal { get; set; }
        public string GrandTotal { get; set; }
        public string DeliveryDate { get; set; }
        public string SubmitDate { get; set; }
        public string pleaseentermobileNos { get; set; }
        public string Mappingalreadyexist { get; set; }
        public string Selectatleastonegroup { get; set; }
        public string CampaignUpdatedSuccessfully { get; set; }
        public string QuickSMSUpdatedSuccessfully { get; set; }
        public string PleaseselectatleastoneRecipienttoSubmitaQuickSMS { get; set; }
        public string AlreadyexistedsamerecordinActivestatus { get; set; }
        public string Failed { get; set; }
        public string OperatorPrId { get; set; }
        public string Total { get; set; }
        public string Pleaseactivethisfeature { get; set; }

        public string Pleaseenterrole { get; set; }
        public string SynapseUser { get; set; }
        public string InValidseries { get; set; }
        public string PauseEnable { get; set; }
        public string ResumeEnable { get; set; }
        public string DisableRow { get; set; }
        public string FilterWordsView { get; set; }
        public string FeaturesNotAvailableForSelectedCustomers { get; set; }
        public string Areyousureyouwanttodeleteexistingrecordsforsamecustomeranduser { get; set; }
        public string ON { get; set; }
        public string OFF { get; set; }
        public string ModulewiseReports { get; set; }
        public string Periodofstartenddatesshouldntbenull { get; set; }
        public string PleaseEnterValueInMSISDNOrMSGID { get; set; }
        public string NoCampaignsSelected { get; set; }
        public string Pleaseenterminimum5digits { get; set; }
        public string Close { get; set; }
        public string FailedToInactiveContactsAreActiveInThisGroup { get; set; }
        public string SendQuery { get; set; }
        public string Areyousureyouwanttoproceedwithselectednumbers { get; set; }
        public string Uploadfilecontainsdotsinfilename { get; set; }
        public string Contactsareactiveinthisgroup { get; set; }
        public string LastExecutionDate { get; set; }
        public string TotalRecipientCount { get; set; }
        public string Areyousure { get; set; }
        public string record { get; set; }
        public string CreateOfflineAlerts { get; set; }
        public string OfflineAlertsView { get; set; }
        public string CreateOnlineAlerts { get; set; }
        public string DeliveryRequired { get; set; }
        public string OnlineAlertsView { get; set; }
        public string CreateTemplate { get; set; }
        public string UserMappingView { get; set; }
        public string TemplateUserMapareadyExists { get; set; }
        public string AlertDescription { get; set; }
        public string Profile { get; set; }
        public string LdapUser { get; set; }
        public string MsgSubmittedToChecker { get; set; }
        public string TestMail { get; set; }
        public string ThisisfortestingSMTPmail { get; set; }
        public string AddHLRLookup { get; set; }
        public string LookUpEnabledForCampaigns { get; set; }
        public string LookUpEnabledForAlerts { get; set; }
        public string MinimumPeriodtoHoldSMS { get; set; }
        public string LookupShouldbeAttemptedafterdays { get; set; }
        public string pleaseenterlookupdays { get; set; }
        public string SendSMSinRoaming { get; set; }
        public string HLRLookupView { get; set; }
        public string ApplicationConfiguration { get; set; }
        public string PleaseEnterValuedData { get; set; }
        public string AuditLogs { get; set; }
        public string MinimumPeriod { get; set; }
        public string Successfullyuploadcompleted { get; set; }
        public string HlrView { get; set; }
        public string EnableLookUp { get; set; }
        public string DisableLookUp { get; set; }
        public string pleaseenterminimumperiodtoholdsms { get; set; }
        public string SMS { get; set; }

        public string Static { get; set; }

        public string Dynamic { get; set; }

        public string PleaseEnterCount { get; set; }

        public string PleaseenterOperator { get; set; }

        public string PleaseEnterVendorName { get; set; }

        public string PleaseEnterHostName { get; set; }


        public string PleaseSelectSenderId { get; set; }


        public string WW { get; set; }


        public string FeatureList { get; set; }
        public string SNO { get; set; }
        public string PleaseaddatleastoneIPorcheckAnyIPAddress { get; set; }
        public string MobileNumberwithISDcode { get; set; }
        public string SyncConfigurations { get; set; }
        public string SyncSMSCconfigurations { get; set; }
        public string SyncUserconfigurations { get; set; }
        public string ClientConfigCreatedSuccessfully { get; set; }
        public string MODetailedRCReport { get; set; }
        public string MODetailedRC { get; set; }
        public string ValidateSSLTSL { get; set; }
        public string Ex971XXXXXXX { get; set; }
        public string PleaseSelectMailbox { get; set; }

        public string PleaseSelectInterval { get; set; }
        public string PleaseSelectemailtemplate { get; set; }

        public string PleaseSelectCustomerType { get; set; }
        public string InvalidInputParameters { get; set; }

        public string SuccessfullyInactived { get; set; }
        public string SuccessfullyActived { get; set; }
        public string PleasseEnterName { get; set; }
        public string AlertUpdatedSuccessfully { get; set; }
        public string AlertsManager { get; set; }
        public string ServiceNameSID { get; set; }
        public string Edit { get; set; }
        public string UsageAnalysis { get; set; }
        public string SearchCampaigns { get; set; }
        public string NoContactsinSelectedGroup { get; set; }
        public string Invalidcampaigncount { get; set; }
        public string youcannotsubmitthecampaignWith0credits { get; set; }
        public string FileAlerts { get; set; }
        public string DBAlerts { get; set; }
        public string CreateFileAlerts { get; set; }
        public string CreateDBAlerts { get; set; }
        public string FileAlertsView { get; set; }
        public string DBAlertsView { get; set; }
        public string FileAlertsavedSuccessfully { get; set; }
        public string DBAlertsavedSuccessfully { get; set; }
        public string FileAlertalreadyexists { get; set; }
        public string DBAlertalreadyexists { get; set; }

        public string PushNotification { get; set; }
        public string RegisterEmailAddress { get; set; }
        public string MapEmail { get; set; }
        public string EmailCampaign { get; set; }
        public string EmailAnalysis { get; set; }
        public string AppRegistration { get; set; }
        public string PushNotificationCampaign { get; set; }
        public string NotificationAnalysis { get; set; }
        public string RegisterEmail { get; set; }
        public string RegisteredEmails { get; set; }
        public string Mappings { get; set; }
        public string ComposeEmailCampaign { get; set; }
        public string EmailCampaigns { get; set; }
        public string SearchCampaign { get; set; }
        public string Registration { get; set; }
        public string Registrations { get; set; }
        public string ComposePushNotificationCampaign { get; set; }
        public string TestPushNotification { get; set; }
        public string FromMailID { get; set; }
        public string MessageType { get; set; }
        public string SecretKey { get; set; }
        public string SecretKeyLabel { get; set; }
        public string PhoneType { get; set; }
        public string MessageBody { get; set; }
        public string DeviceIds { get; set; }
        public string EnterName { get; set; }
        public string PleaseSelectFromMail { get; set; }
        public string PleaseEnterFromMail { get; set; }
        public string PleaseSelectMessageType { get; set; }
        public string PleaseEnterMessageBody { get; set; }
        public string PleaseEnterSecretKey { get; set; }
        public string PleaseEnterSecretKeyLabel { get; set; }
        public string PleaseSelectPhoneType { get; set; }
        public string NotePleaseenterCommaseperatedemailswithoutspace { get; set; }
        public string SuccessfullyFromEmailCreated { get; set; }
        public string SuccessfullyFromEmailMapped { get; set; }
        public string MappingAlreayExistedinDb { get; set; }
        public string SuccessfullyFromEmailMappingupdated { get; set; }
        public string RecipientCount { get; set; }
        public string TotalEmailCount { get; set; }
        public string Detailed { get; set; }
        public string KeyLabel { get; set; }
        public string TotalPNCount { get; set; }
        public string TestEmail { get; set; }
        public string TestNotification { get; set; }
        public string FailedtoActiveContactsAreActiveinThisGroup { get; set; }
        public string SelectedContactnumbercannotbeactivatedasgroupisinInactivestatus { get; set; }
        public string TotalContactsCount { get; set; }
        public string NoOfActiveContacts { get; set; }
        public string SenderConfiguration { get; set; }
        public string Unabletoupdateactivemappingsfound { get; set; }
        public string CampaigncreatedSuccessfully { get; set; }
        public string Fatalerror { get; set; }
        public string BusinessRuleStatistics { get; set; }
        public string Today { get; set; }
        public string DateRange { get; set; }
        public string UserList { get; set; }
        public string Module { get; set; }
        public string Query { get; set; }
        public string Pending { get; set; }
        public string Undelivered { get; set; }
        public string Statistics { get; set; }
        public string SN { get; set; }
        public string UnabletoactivateasMailSettingsareinactive { get; set; }
        public string Updatedsuccessfullyfoundsomewaitingscheduledcampaingns { get; set; }
        public string TestMailSubmittedsuccessfully { get; set; }
        public string FailedtoSubmitTestMail { get; set; }
        public string InvalidDeviceidscount { get; set; }
        public string Fromemailshouldnotempty { get; set; }
        public string Pleaseselectrequiredfields { get; set; }
        public string Mailidscountshouldnotbemorethan50 { get; set; }
        public string Theirisnovalidemailspleasechecktheenteredemailids { get; set; }
        public string Invalidparammetervalue { get; set; }
        public string PleaseselectAccountManager { get; set; }
        public string SenderConfigurationView { get; set; }
        public string IPWhitelist { get; set; }
        public string AppType { get; set; }
        public string IPWhitelistView { get; set; }
        public string Youruseraccountdoesnthavetemplatespleasecontactadministrator { get; set; }
        public string SummaryReport { get; set; }
        public string FunctionalStatus { get; set; }
        public string PriceUpdateHistory { get; set; }
        public string WholeVendorRate { get; set; }
        public string WholeCountryRate { get; set; }
        public string Sender_Type { get; set; }
        public string LandingCostInAED { get; set; }
        public string NewRate { get; set; }
        public string OldRate { get; set; }
        public string GetData { get; set; }
        public string UpdatedOn { get;set; }
        public string PleaseEnterLandingCost { get; set; }
        public string OperatorId { get; set; }
        public string VendorId { get; set; }
        public string SMSCId { get; set; }
        public string OperatorNotExist { get; set; }
        public string SMSCNotExist { get; set; }
        public string CheckHLR { get; set; }
    }
}
